#!/bin/bash
# Author Oraclesstriker
# Purpose to install docker

set -e
clear

GREEN=$'\e[0;32m'
YELLOW=$'\e[0;33m'
RED=$'\e[0;31m'
NC=$'\e[0m'
ME=whoami

if [[ $EUID -eq 0 ]]; then
  echo "${RED}[X]This script must NOT be run as root or sudo![X]" 1>&2
  exit 1
fi

echo "${YELLOW}[!]oraclesstriker brings you the raspberry pi docker initalisation script."
curl -sSL https://get.docker.com | sh
echo "${YELLOW}[+]Adding you to the docker group"
sudo usermod -aG docker $ME
echo "${YELLOW}[+]updating and upgrading your pi"
sudo apt-get update -y
sudo apt-get upgrade -y
echo "${YELLOW}[+]installing the required prerequisites"
sudo apt-get install libffi-dev libssl-dev python3-dev python3 python3-pip -y
sudo pip3 install docker-compose -y
echo "${YELLOW}[!]Rebooting your system now!"
sleep 5
sudo reboot now